### ISSUE TITLE
Crash when changing skin

### ISSUE THREAD

**Issue by kotmatross28729** [trollogyadherent/OfflineAuth#1]
So, I put the mod on the server and it started without problems, but when I went to the client and tried to change the skin, it gave me this:
[crash-2022-08-06_10.04.15-client.txt](https://github.com/trollogyadherent/OfflineAuth/files/9275123/crash-2022-08-06_10.04.15-client.txt)

**Comment by trollogyadherent** [comment]
a fix for this issue is already in the works, thank you for reporting

**Comment by kotmatross28729** [comment]
Ok, thanks for answer

**Comment by trollogyadherent** [comment]
[553431d](https://github.com/trollogyadherent/OfflineAuth/commit/9cec69755d4654554db1238a58b7826b3fcd802b) should fix this.
Latest release: [https://github.com/trollogyadherent/OfflineAuth/releases/tag/v0.2.75](https://github.com/trollogyadherent/OfflineAuth/releases/tag/v0.2.75)
