### ISSUE TITLE
 crash on user registration

### ISSUE THREAD

**Issue by kotmatross28729** [trollogyadherent/OfflineAuth#10]

**Comment by kotmatross28729** [comment]
This happens if I click on something in the offlineauth menu

**Comment by trollogyadherent** [comment]
Crash report is irrelevant to offlineauth, it's a duplicate potion ID.
crash report is a nullpointer exception, and I'm curious how it occured. I added a check for it, I hope it helps
[offlineauth-mc1.7.10-0.2.95b.zip](https://github.com/trollogyadherent/OfflineAuth/files/9995026/offlineauth-mc1.7.10-0.2.95b.zip)

**Comment by kotmatross28729** [comment]
Oops, I messed up the crash report, it's from September 25

like this is him: 
[crash-2022-11-11_22.10.06-client.txt](https://github.com/trollogyadherent/OfflineAuth/files/9995106/crash-2022-11-11_22.10.06-client.txt)

**Comment by kotmatross28729** [comment]
oh that fixed it

**Comment by kotmatross28729** [comment]
(Thanks)
