### ISSUE TITLE
User can join server by not using the mod client side

### ISSUE THREAD

**Issue by Gughy14** [trollogyadherent/OfflineAuth#11]
Custom modpack for private server, we were doing some tests. Using thermos with forge 1614.
We found out you are able to join the server without any authentication/security check by simply removing the mod client side.

[log.txt](https://github.com/trollogyadherent/OfflineAuth/files/9996049/log.txt)

**Comment by trollogyadherent** [comment]
thermos is not supported atm. it does a lot of fuckery with ASM that breaks a lot of mods and plugins

**Comment by trollogyadherent** [comment]
I have in mind rewriting some plugins for forge, because that would be way easier than dealing with the thermos mess

**Comment by Gughy14** [comment]
Out of mere curiosity I tired replicating the issue with a plain forge server with nothing else and it still presents the same behaviour.
[fml-server-latest.log](https://github.com/trollogyadherent/OfflineAuth/files/10005922/fml-server-latest.log)

**Comment by kotmatross28729** [comment]
> I have in mind rewriting some plugins for forge, because that would be way easier than dealing with the thermos mess
[world guard](https://dev.bukkit.org/projects/worldguard) as mod for forge 1.7.10 + already existing [world edit](https://www.curseforge.com/minecraft/mc-mods/worldedit)? (or its fork on github for better compatibility?)...........?

**Comment by trollogyadherent** [comment]
are there issues with 1.7.10 world edit? I remember using it without problem. worldguard looks interesting, I might try to see in the future. atm I'm finishing to backport eyes in the darkness

**Comment by kotmatross28729** [comment]
no, the worldedit mod is ok, it's just that world guard (as a plugin) is... an addon for world edit.?
I figured that if you want to port world guard as a forge mod, it will need to be compatible with world edit as a mod, like the ftb libruary and offlineauth.
I just don't know how it works, sorry if it doesn't.

**Comment by trollogyadherent** [comment]
Oh ok, I get it. Yeah a mod like worldguard would have to get a lot of work put into making it compatible with a bunch of mods.
I'm porting the eyes mods because 1) I really like the concept (will try to make a warp effect that spawns them) 2) Wanted to learn a bit more about living entity modding.

I like the discussions here but I don't think Gughy enjoys the notifications :joy:. You can always make a new issue or write on matrix.
