### ISSUE TITLE
User can join server by not having the mod client side

### ISSUE THREAD

**Issue by Gughy14** [trollogyadherent/OfflineAuth#12]
Out of mere curiosity I tired replicating the issue #11 in a testing environment; I set up a plain forge server with no other mods or whatsoever and the same behaviour still occurs.

Here is the related log:
[fml-server-latest.log](https://github.com/trollogyadherent/OfflineAuth/files/10006038/fml-server-latest.log)

**Comment by trollogyadherent** [comment]
I could reproduce the issue, the bug must have been introduced when I was doing some packet code reshuffling, thanks for reporting back, working on a fix

**Comment by trollogyadherent** [comment]
https://github.com/trollogyadherent/OfflineAuth/releases/tag/v0.2.96 should fix it, please tell when you have time to test

**Comment by Gughy14** [comment]
Perfect! v.0.2.96 fixed it.
