### ISSUE TITLE
Heavy modpack's and/or slow system's users are kicked from the server

### ISSUE THREAD

**Issue by Gughy14** [trollogyadherent/OfflineAuth#13]
For users with slow computer/network or heavy modpacks, the player gets kicked before it actually joins the server.
This is related to solution for #12 which added a 5 seconds timeout for the authentication packet to be received.
In the aforementioned cases, more than 5 seconds may be necessary to complete the connection, resulting in the kick of the player from the server.

**Comment by trollogyadherent** [comment]
I'll make the timeout configurable, just not today, it's a bit late

**Comment by trollogyadherent** [comment]
https://github.com/trollogyadherent/OfflineAuth/releases/tag/v0.2.98 should fix it. I will work on mixining into the vanilla auth packet so unauthed players aren't even granted a player object ingame (for now all their events get cancelled)
