### ISSUE TITLE
Problem with translation

### ISSUE THREAD

**Issue by kotmatross28729** [trollogyadherent/OfflineAuth#2]
Its me again. Today I wanted to translate the mod into Russian, but I ran into some problems:

There is no translation option for these settings in the file
![Base Profile Screenshot 2022 08 07 - 17 09 36 73](https://user-images.githubusercontent.com/110309314/183295036-2e146c9a-142d-4074-ae89-6994b20246ee.png)
And wrong button size for registration
(the rest goes beyond the screen borders (I don't know if it's possible to fix this))
![Base Profile Screenshot 2022 08 07 - 17 09 46 60](https://user-images.githubusercontent.com/110309314/183295153-ea6af0bf-e682-4485-b281-240baaec88bc.png)

**Comment by trollogyadherent** [comment]
should be good with [4f72d19](https://github.com/trollogyadherent/OfflineAuth/commit/4f72d1975a5c123eddf0ee9f924f866a08111336)
![image](https://user-images.githubusercontent.com/19153947/183310135-972ab561-ce2e-453e-af02-eb9e80e10f48.png)
