### ISSUE TITLE
offlineauth-0.2.75.jar is marked as a Fabric release

### ISSUE THREAD

**Issue by floral-qua-floral** [trollogyadherent/OfflineAuth#3]
[Link to file on Curseforge](https://www.curseforge.com/minecraft/mc-mods/offlineauth/files/3923718)

This causes OfflineAuth to show up when filtering for Fabric mods, which isn't ideal.

**Comment by trollogyadherent** [comment]
yes, I just saw it and fixed it. silly mistake
