### ISSUE TITLE
It happened again

### ISSUE THREAD

**Issue by kotmatross28729** [trollogyadherent/OfflineAuth#4]
Today I wanted to test the new version, and again I wanted to change the skin, but for some reason he gave me this (a little different than last time)
[crash-2022-08-08_09.35.20-client.txt](https://github.com/trollogyadherent/OfflineAuth/files/9279336/crash-2022-08-08_09.35.20-client.txt)

EDIT: I made a completely Russian version :
[ru_RU.zip](https://github.com/trollogyadherent/OfflineAuth/files/9279504/ru_RU.zip)

EDIT2: I have now deleted the offlineauth folder in the client folder and it worked, I don't know why.

EDIT3: it's like a ClientKeyCache, or a ClientCache in a folder.

EDIT4 : I FOUND. ITS BEEN  "serverdata.json"

**Comment by trollogyadherent** [comment]
```java
if (oasd.isUsingKey()) {
                            try {
                                clientPubKey = RsaKeyUtil.loadPublicKey(oasd.getPublicKeyPath());
                                clientPriv = RsaKeyUtil.loadPrivateKey(oasd.getPrivateKeyPath());
                            } catch (IOException | NoSuchAlgorithmException | InvalidKeySpecException e) {
                                throw new RuntimeException(e);
                            }
                        }
                        ```
It throws the exception here. It seems like java can't access your key files? this is weird, I'll do some tests

**Comment by trollogyadherent** [comment]
I just tested on my side and I cannot reproduce the issue. I have added code that prevents a hard crash though. Leaving open for now

**Comment by kotmatross28729** [comment]
I think that this can also be closed, in new versions it does not crash
