### ISSUE TITLE
can't login to my server [FORGE]

### ISSUE THREAD

**Issue by kotmatross28729** [trollogyadherent/OfflineAuth#7]
![12345](https://user-images.githubusercontent.com/110309314/195306179-24d6ccbe-b753-45d4-8f96-ccbc6db932c0.png)
![123456789](https://user-images.githubusercontent.com/110309314/195306191-e1e63ade-52e7-4718-a852-bc7d78a05907.png)

https://user-images.githubusercontent.com/110309314/195306477-603f4599-b979-4357-8112-850b26cdee87.mp4

EDIT: yeah, now there is an endless registration check

https://user-images.githubusercontent.com/110309314/195307996-ef1c41a7-2549-48e4-8e70-d6bb8634c812.mp4

EDIT2:  
Now everything is the same as it was in the beginning

https://user-images.githubusercontent.com/110309314/195680140-eb84b4f1-14d1-4f09-8832-cefe9e2636b6.mp4

EDIT3: I set only offlineauth and in the logs it writes this:

[fml-server-latest.log](https://github.com/trollogyadherent/OfflineAuth/files/9779685/fml-server-latest.log)

https://user-images.githubusercontent.com/110309314/195683791-3191d04f-2520-4f8f-8a72-53de20d25848.mp4

**Comment by kotmatross28729** [comment]
@trollogyadherent

**Comment by trollogyadherent** [comment]
thanks for the report, sorry for replying this late, I was quite busy with life. you will also reach me faster on matrix.
Would it be possible for you to send me your database? it's the `OfflineAuthDatabase` folder. It contains no passwords, only hashes and salts. Something goes wrong when the mod tries to retrieve the user object from the database

**Comment by kotmatross28729** [comment]
it's in the server folder, right?
[Database server.zip](https://github.com/trollogyadherent/OfflineAuth/files/9927266/Database.server.zip)

**Comment by trollogyadherent** [comment]
I'll look at it when I get home, but for now my phone can't open it. 2 archive utilitites complain about corrupted zip.

**Comment by trollogyadherent** [comment]
```
~/Downloads ❯ unzip Database.server.zip
Archive:  Database.server.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of Database.server.zip or
        Database.server.zip.zip, and cannot find Database.server.zip.ZIP, period
```
Tried at school, neither gui nor command line works. Download and compare checksum, or compress and upload again 🤷

**Comment by kotmatross28729** [comment]
[OfflineAuthDatabase.zip](https://github.com/trollogyadherent/OfflineAuth/files/9929524/OfflineAuthDatabase.zip)

**Comment by trollogyadherent** [comment]
I investigated the issue, on my side it works fine.
```
playerex Globys2
[07:12:33] [Server thread/INFO]: User registered (Globys2 is the identifier)
[07:12:33] [Server thread/INFO] [offlineauth]: DEBUG: Data ~ Identifier: Globys2 ~ Displayname: Artem2
[07:12:33] [Server thread/INFO] [offlineauth]: Server issued playerexists command
playerex Artem2
[07:12:39] [Server thread/INFO]: User registered (Artem2 is the displayname)
[07:12:39] [Server thread/INFO] [offlineauth]: DEBUG: Data ~ Identifier: Globys2 ~ Displayname: Artem2
[07:12:39] [Server thread/INFO] [offlineauth]: Server issued playerexists command
```
I added code to catch the nullpointer exception you got and inserted a couple of debug prints that will maybe tell more. Please try the attached build and send a log:

[Uploading offlineauth-mc1.7.10-0.2.89_debug.zip…]()

**Comment by kotmatross28729** [comment]
my server crashes on startup:

[fml-server-latest.log](https://github.com/trollogyadherent/OfflineAuth/files/9936437/fml-server-latest.log)

**Comment by trollogyadherent** [comment]
[offlineauth-mc1.7.10-0.2.89_debug2.zip](https://github.com/trollogyadherent/OfflineAuth/files/9936561/offlineauth-mc1.7.10-0.2.89_debug2.zip)
Weird, try this

**Comment by kotmatross28729** [comment]
oh it works

**Comment by kotmatross28729** [comment]
Now I can log into the server, thanks!

**Comment by trollogyadherent** [comment]
I'll give it some time and then do a release. I am not sure why a null pointer exception occurred in your case and the problem might manifest again, let's hope it doesn't.
