### ISSUE TITLE
minecraft crashes when exiting single player

### ISSUE THREAD

**Issue by kotmatross28729** [trollogyadherent/OfflineAuth#9]
### description:
 **when offlineauth is installed and i exit the menu from singleplayer minecraft crashes**
### version:
 **offlineauth-mc1.7.10-0.2.89_debug2**
### Log:

[latest.log](https://github.com/trollogyadherent/OfflineAuth/files/9937899/latest.log)

**Comment by trollogyadherent** [comment]
Oh, I might have an idea on why that happens., I'll check when I can

**Comment by trollogyadherent** [comment]
[offlineauth-mc1.7.10-rc-0.2.91.zip](https://github.com/trollogyadherent/OfflineAuth/files/9944403/offlineauth-mc1.7.10-rc-0.2.91.zip)
this should fix it (https://github.com/trollogyadherent/OfflineAuth/commit/5fade7e0121b116ca6f757db24c9f83a5c0f01f8).
I added closing the database object on server shutdown, just in case not doing so would corrupt it. I forgot to not do it in singleplayer.

**Comment by kotmatross28729** [comment]
oh it works now, thanks!
